project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2122/*"
    - "!10*"
    - "!11*"
  output-dir: ../docs/2223/labs/

website:
  title: "DAPR3"
  navbar:
    left:
    - text: "Multi Level Models"
      menu:
        - text: "1: Linear Regression | Clustered Data"
          href: 01_regressionrefresh.html
        - text: "2: Multilevel Models"
          href: 02_intromlm.html
        - text: "3: Assumptions, Diagnostics & Random Effect Structures"
          href: 03_assumptranef.html
        - text: "4: Centering in MLM | Logistic"
          href: 04_centerglmer.html
        - text: "5: Recap"
          href: 05_recap.html
    - text: "Dimension reduction & SEM"
      menu:
        - text: "7: Path Analysis"
          href: 07_path1.html
        - text: "8: Path Mediation"
          href: 08_path2.html
        - text: "9: Dimension Reduction"
          href: 09_pca.html
        - text: "10: EFA: Part 1"
          href: 10_efa.html
        - text: "11: EFA: Part 2"
          href: 11_efa2.html
    right:
    - text: "Extra"
      menu: 
        - text: "Example: Repeated Measures MLM"
          href: example_01_repeated_measures.html
        - text: "Example: Intervention Study"
          href: example_02_intervention.html
        - text: "Example: Many Trials"
          href: example_03_many_trials.html
        - text: "Example: ANOVA (rpt measures & mixed)"
          href: example_00_anova.html
        - text: "Example: Exploratory Factor Analysis"
          href: example2_01_EFA.html
        - text: "Likelihood vs Probability"
          href: lvp.html
        - text: "Writing 3-level MLM equations"
          href: explainer_3leveleq.html
        - text: "PCA and Unequal Variances"
          href: explainer_pcavar.html

format:
  html:
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    number-sections: false
    code-copy: false


