project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2122/*"
    - "!archive_2223/*"
    - "!archive_2324/*"
    - "!archive_msmr_2324/*"
  output-dir: ../docs/2425/labs/

website:
  title: "DAPR3"
  page-footer: © Copyright 2019-2024 [The University of Edinburgh](https://www.ed.ac.uk/). Site licensed under the [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) license.  
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - section: "Multilevel Model Readings"
        contents:
          - 01a_clustered.qmd
          - 01b_lmm.qmd
          - 05a_assump.qmd
          - 04a_ranef.qmd
          - 05b_writing.qmd
      - section: "Multilevel Models Exercises"
        contents:
          - 01ex.qmd
          - 02ex.qmd
          - 03ex.qmd
          - 04ex.qmd
          - 05ex.qmd
      - section: "Factor Analysis Readings"
        contents:
      - section: "Factor Analysis Exercises"
        contents:

format:
  html:
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    link-citations: true
    number-sections: false
    code-copy: false


