project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2122/*"
    - "!archive_2223/*"
    - "!10*"
    - "!11*"
  output-dir: ../docs/2324/labs/

website:
  title: "DAPR3"
  page-footer: © Copyright 2019-2023 [The University of Edinburgh](https://www.ed.ac.uk/). Site licensed under the [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) license.  
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - section: "Multilevel Models"
        contents:
          - 01_regressionrefresh.qmd
          - 02_intromlm.qmd
          - 03_assumptcent.qmd
          - 04_ranefglmer.qmd
          - 05_recap.qmd
          - 05b_lmmdatasets.qmd
          - section: "Additional Docs"
            contents:          
              - example_00_anova.qmd
              - lvp.qmd
              #- example_01_repeated_measures.qmd
              #- example_02_intervention.qmd
              #- example_03_many_trials.qmd
      - section: "- Break Week -"
      - section: "Path Analysis and Data Reduction"
        contents:          
          - 07_path1.qmd
          - 08_path2.qmd
          - 09_pca.qmd
          - "10. EFA I"
          #- 10_efa.qmd
          - "11. EFA II"
          #- 11_efa2.qmd
          - section: "Additional Docs"
            contents:          
              #- explainer_pcavar.qmd
              #- example2_01_EFA.qmd
              #- explainer_3leveleq.qmd
              
format:
  html:
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    link-citations: true
    number-sections: false
    code-copy: false


