project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2122/*"
    - "!archive_2223/*"
  output-dir: ../docs/2324/labs/

website:
  title: "DAPR3"
  page-footer: © Copyright 2019-2023 [The University of Edinburgh](https://www.ed.ac.uk/). Site licensed under the [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) license.  
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "Multilevel Models"
        contents:
          - 01_regressionrefresh.qmd
          - 02_intromlm.qmd
          - 03_assumptranef.qmd
          - 04_centerglmer.qmd
          - 05_recap.qmd
      - section: "Path Analysis and Data Reduction"
        contents:          
          - 07_path1.qmd
          - 08_path2.qmd
          - 09_pca.qmd
          - 10_efa.qmd
          - 11_efa2.qmd
      - section: "Additional Docs"
        contents:          
          - example_01_repeated_measures.qmd
          - example_02_intervention.qmd
          #- example_03_many_trials.qmd
          - example_00_anova.qmd
          #- example2_01_EFA.qmd
          - lvp.qmd
          #- explainer_3leveleq.qmd
          #- explainer_pcavar.qmd

format:
  html:
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    link-citations: true
    number-sections: false
    code-copy: false


