project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2324/*"
    - "!archive_msmr_2324/*"
  output-dir: ../docs/2526/labs/

website:
  title: "DAPR3 Lab Exercises"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - 00prereq.qmd


format:
  html:
    page-layout: full
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    link-citations: true
    number-sections: false
    code-copy: true


