project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2122/*"
    - "!archive_2223/*"
    - "!archive_2324/*"
    - "!archive_msmr_2324/*"
  output-dir: ../docs/2425/labs/

website:
  title: "DAPR3 Lab Exercises"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - 00prereq.qmd
      - 01ex.qmd
      - 02ex.qmd
      - 03ex.qmd
      - 04ex.qmd
      - 05ex.qmd
      - "- break week -"
      - section: "Week 7"
        contents:
         - r07_qdata.qmd
         - 07ex.qmd
      - section: "Week 8"
        contents:
         - r08_pca.qmd
         - 08ex.qmd
      - section: "Week 9"
        contents:
         - r09_efa.qmd
         - 09ex.qmd
      - section: "Week 10"
        contents:
         - 10ex.qmd
      - section: "Week 11"
        contents:
         - 11ex.qmd


format:
  html:
    page-layout: full
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    link-citations: true
    number-sections: false
    code-copy: true


